AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 buckets'

Parameters:
  BucketName:
    Type: String
    Description: Name for the raw data S3 bucket
    Default: imbastanley1987

Resources:
  RawDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
    DeletionPolicy: 'Retain'

Outputs:
  BucketName:
    Description: 'Name of the raw data S3 bucket'
    Value: !Ref BucketName