name: Deploy AWS Resources

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  
#      workflow_dispatch: # Trigger manually on workflow


jobs:
  deploy_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy S3 Buckets CloudFormation Stack
        id: s3-buckets
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.4
        with:
          name: imba-RawDataBucket
          template: cfn/s3.yml
          capabilities: CAPABILITY_IAM